Thought i broke everything
i forgot to commit and push run and pulled everything and deleted my changes for the hardcoding but managed to salvage it

diff --git a/run b/run
--- a/run
+++ b/run
@@ -5,54 +5,54 @@ export LOG_LEVEL="2"
 
 # Check the first argument to the script
 if [ "$1" == "install" ]; then
-    echo "Running installation..."
-    echo "Installing ts-node"
+    #echo "Running installation..."
+    #echo "Installing ts-node"
     npm install ts-node --save
-    echo "Ts-node installed."
-    echo "Installing yargs"
+    #echo "Ts-node installed."
+    #echo "Installing yargs"
     npm install yargs --save
-    echo "Yargs installed."
-    echo "Installing axios"
+    #echo "Yargs installed."
+    #echo "Installing axios"
     npm install axios --save
-    echo "Axios installed."
-    echo "Installing child_process"
+    #echo "Axios installed."
+    #echo "Installing child_process"
     npm install child_process --save
-    echo "Child_process installed."
-    echo "Installing path"
+    #echo "Child_process installed."
+    #echo "Installing path"
     npm install path --save
-    echo "Path installed."
-    echo "Installing winston"
+    #echo "Path installed."
+    #echo "Installing winston"
     npm install winston --save
-    echo "Winston installed."
-    echo "Ready to run other commands."
+    #echo "Winston installed."
+    #echo "Ready to run other commands."
     exit 0
-elif [ "$1" == "URL_FILE" ]; then
+elif [ -f "$1" ]; then
     rm -rf "cli_storage"/*
-    echo "Clearing local package storage..."
-    echo "Compiling essential scripts..."
+    #echo "Clearing local package storage..."
+    #echo "Compiling essential scripts..."
     tsc metrics.ts
     tsc logger.ts
     tsc npm-github-netscore.ts
-    echo "Scripts compiled."
-    npx ts-node run.ts $@
+    #echo "Scripts compiled."
+    npx ts-node run.ts "URL_FILE" "$1"
+    
     if [ $? -ne 0 ]; then
-      echo "An error occurred. Enable or check logfile for debugging"
+      #echo "An error occurred. Enable or check logfile for debugging"
     exit 1
-    fi
     else
     exit 0
     fi
 elif [ "$1" == "test" ]; then
     npx ts-node run.ts $@
     if [ $? -ne 0 ]; then
-      echo "An error occurred. Must install dependencies!"
-    fi
+      #echo "An error occurred. Must install dependencies!"
+      exit 1
     else
     exit 0
     fi
 else
-    echo "Unknown command: $1"
-    echo "Please us one of these commands: install', 'URL_FILE', or 'test'"
+    #echo "Unknown command: $1"
+    #echo "Please us one of these commands: install', 'URL_FILE', or 'test'"
     exit 1
 fi
 
